# Generated by Django 5.2.7 on 2025-10-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
